name: 'watabot ci'
on:
  push:
    branches: [master]

jobs:
  package:
    name: zip files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "create tmp dir"
        run: |
          mkdir function
          cp go.mod function
          cp bot/*go function

      - name: "upload function.zip"
      - uses: actions/upload-artifact@v3
        with:
          name: function.zip
          path: ./function